{% set name = "piecewise-regression" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/piecewise-regression-{{ version }}.tar.gz
  sha256: 7524e09264ff7180f7641f83b0c5b6a6dd69cc31a6011798b56792370be49ce1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base
    - numpy
    - python >=3.7
    - scipy
    - statsmodels

test:
  imports:
    - piecewise_regression
    - tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chasmani/piecewise-regression
  summary: piecewise (segmented) regression in python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chasmani
